package network.sharering.envelock.demo

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import java.util.concurrent.ArrayBlockingQueue
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject
import uniffi.envelock.FfiRecoveryReason
import uniffi.envelock.FfiVaultException

/**
 * The app's view of the vault: four SDK calls and no envelock import.
 *
 * [MainActivity]'s own screen is the other half of the picture - the raw vault lifecycle, which
 * is what [ShareRingVaultSdk] wraps. Switch between the two at the top of the screen.
 *
 * ## What to watch for
 *
 * - **First launch enrolls silently.** The 12 words are generated by the SDK; the app only ever
 *   asks for them back with `getRecoveryFactor()`.
 * - **The first `getDocument` hits the fake backend, the rest do not.** After that the answer
 *   comes out of the vault, offline, behind one biometric prompt.
 */
@Composable
fun SdkDemoScreen(onReady: (ShareRingVaultSdk?) -> Unit) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    var sdk by remember { mutableStateOf<ShareRingVaultSdk?>(null) }
    var log by remember { mutableStateOf(listOf<String>()) }
    var fatal by remember { mutableStateOf<String?>(null) }
    var typed by remember { mutableStateOf("") }

    // The Rust core calls the recovery provider on a background thread and blocks it. The
    // dialog answers through this queue; a blank answer means the user dismissed it.
    val pending = remember { MutableStateFlow<FfiRecoveryReason?>(null) }
    val answers = remember { ArrayBlockingQueue<String>(1) }
    val prompting by pending.collectAsState()

    fun append(line: String) {
        log = (listOf(line) + log).take(40)
    }

    /** Every SDK call runs off the main thread: unlock blocks on a biometric prompt. */
    fun act(label: String, body: suspend (ShareRingVaultSdk) -> String) = scope.launch {
        val ready = sdk ?: return@launch
        try {
            append("[ok] $label - ${withContext(Dispatchers.IO) { body(ready) }}")
        } catch (e: FfiVaultException.Cancelled) {
            append("- $label - cancelled by user (not counted)")
        } catch (e: FfiVaultException) {
            append("[x] $label - ${e::class.simpleName}: ${e.message}")
        }
    }

    if (sdk == null && fatal == null) {
        LaunchedInitialize(
            initialize = {
                ShareRingVaultSdk.initialize(
                    context,
                    SdkOptions(
                        appId = "demo-miniapp",
                        fetchDocument = ::fakeBackend,
                        vaultOptions = SdkVaultOptions(
                            providerId = "sharering-sdk-demo",
                            // The one thing the app still owns. See DemoProviders.kt for why a
                            // local pepper is not a second factor.
                            material = LocalDemoMaterialProvider(context),
                            promptRecoveryPhrase = { reason ->
                                pending.value = reason
                                answers.take().also { pending.value = null }
                            },
                        ),
                    ),
                )
            },
            onSuccess = {
                sdk = it
                onReady(it)
                append("[ok] initialize - vault open and enrolled")
            },
            onFailure = { fatal = it.toString() },
        )
    }

    Surface(modifier = Modifier.fillMaxSize()) {
        Column(
            modifier = Modifier
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            Text("ShareRing Vault SDK", style = MaterialTheme.typography.headlineMedium)

            fatal?.let {
                Text("SDK failed to initialize:", style = MaterialTheme.typography.titleMedium)
                Text(it, style = MaterialTheme.typography.bodySmall)
                return@Column
            }

            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Button(onClick = {
                    act("getDocument") {
                        val doc = it.getDocument("passport")
                        "${doc.getString("type")} for ${doc.getString("holder")}"
                    }
                }) { Text("Get document") }

                Button(onClick = {
                    act("getRecoveryFactor") { it.getRecoveryFactor() }
                }) { Text("Show phrase") }
            }

            Spacer(Modifier.height(4.dp))
            Text("Danger", style = MaterialTheme.typography.titleMedium)

            Button(onClick = {
                act("destroy") {
                    it.destroy()
                    sdk = null
                    onReady(null)
                    "everything deleted - irreversible"
                }
            }) { Text("Destroy") }

            Spacer(Modifier.height(8.dp))
            Card(modifier = Modifier.fillMaxWidth()) {
                Column(Modifier.padding(12.dp)) {
                    if (log.isEmpty()) {
                        Text("Waiting for initialize...", style = MaterialTheme.typography.bodySmall)
                    }
                    log.forEach { Text(it, style = MaterialTheme.typography.bodySmall) }
                }
            }
        }
    }

    prompting?.let { reason ->
        AlertDialog(
            onDismissRequest = { answers.offer("") },
            title = { Text("Enter your 12 words ($reason)") },
            text = {
                OutlinedTextField(
                    value = typed,
                    onValueChange = { typed = it },
                    placeholder = { Text("abandon ability able ...") },
                )
            },
            confirmButton = {
                TextButton(onClick = { answers.offer(typed) }) { Text("Recover") }
            },
            dismissButton = {
                // Dismissing is normal behaviour, not a failed attempt.
                TextButton(onClick = { answers.offer("") }) { Text("Cancel") }
            },
        )
    }
}

/** Run a blocking initialize once, off the main thread. */
@Composable
private fun LaunchedInitialize(
    initialize: () -> ShareRingVaultSdk,
    onSuccess: (ShareRingVaultSdk) -> Unit,
    onFailure: (Throwable) -> Unit,
) {
    androidx.compose.runtime.LaunchedEffect(Unit) {
        runCatching { withContext(Dispatchers.IO) { initialize() } }
            .onSuccess(onSuccess)
            .onFailure(onFailure)
    }
}

/** Stands in for the ShareRing network. Called once per document, ever. */
private fun fakeBackend(documentId: String): ByteArray =
    JSONObject()
        .put("id", documentId)
        .put("type", "identity.passport")
        .put("holder", "Ada Lovelace")
        .put("issuedAt", java.util.Date().toString())
        .toString()
        .toByteArray()
