// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum WireMaterialReason: Int {
  case enroll = 0
  case unlock = 1
  case rotate = 2
}

enum WireRecoveryReason: Int {
  case migrate = 0
  case fallback = 1
  case change = 2
}

enum WireHardwareBacking: Int {
  case secureEnclave = 0
  case strongBox = 1
  case tee = 2
  case software = 3
}

enum WireRecoveryKind: Int {
  case highEntropy = 0
  case passphrase = 1
}

enum WireVaultState: Int {
  case notEnrolled = 0
  case locked = 1
  case unlocked = 2
  case lockedOut = 3
  case needsRecovery = 4
}

/// How a provider rejected (spec 7.4).
///
/// Only [denied] counts toward lockout. Anything unrecognised is treated as [unavailable]:
/// retryable, because a flaky network must never march a legitimate user toward lockout.
enum WireErrorCode: Int {
  case cancelled = 0
  case unavailable = 1
  case denied = 2
  case misconfigured = 3
  case providerMaterialMismatch = 4
  case providerKeyRotated = 5
  case materialRejected = 6
  case corruptData = 7
  case unexpected = 8
}

/// Generated class from Pigeon that represents data sent in messages.
struct WireVaultConfig {
  /// Namespaced into derivation. Changing it invalidates every existing vault.
  var providerId: String
  /// App-private storage. Null lets the platform choose.
  var directory: String? = nil
  /// Inactivity timeout before the DEK is zeroized. `0` disables auto-lock.
  var autoLockMs: Int64
  var callbackDeadlineMs: Int64
  /// Failed recovery attempts before destruction. Null disables it. Passphrase vaults only.
  var destroyAfterAttempts: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireVaultConfig? {
    let providerId = pigeonVar_list[0] as! String
    let directory: String? = nilOrValue(pigeonVar_list[1])
    let autoLockMs = pigeonVar_list[2] as! Int64
    let callbackDeadlineMs = pigeonVar_list[3] as! Int64
    let destroyAfterAttempts: Int64? = nilOrValue(pigeonVar_list[4])

    return WireVaultConfig(
      providerId: providerId,
      directory: directory,
      autoLockMs: autoLockMs,
      callbackDeadlineMs: callbackDeadlineMs,
      destroyAfterAttempts: destroyAfterAttempts
    )
  }
  func toList() -> [Any?] {
    return [
      providerId,
      directory,
      autoLockMs,
      callbackDeadlineMs,
      destroyAfterAttempts,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WireVaultHandle {
  var vaultId: String
  /// The resolved storage directory.
  var directory: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireVaultHandle? {
    let vaultId = pigeonVar_list[0] as! String
    let directory = pigeonVar_list[1] as! String

    return WireVaultHandle(
      vaultId: vaultId,
      directory: directory
    )
  }
  func toList() -> [Any?] {
    return [
      vaultId,
      directory,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WireStateResult {
  var state: WireVaultState
  var lockedUntilMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireStateResult? {
    let state = pigeonVar_list[0] as! WireVaultState
    let lockedUntilMs: Int64? = nilOrValue(pigeonVar_list[1])

    return WireStateResult(
      state: state,
      lockedUntilMs: lockedUntilMs
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      lockedUntilMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WireMaterialContext {
  var vaultId: String
  var requestId: String
  var reason: WireMaterialReason
  /// 32 fresh bytes for challenge-response with your own backend. envelock never inspects any
  /// response; nothing in the key hierarchy depends on it.
  var nonce: FlutterStandardTypedData
  var deadlineMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireMaterialContext? {
    let vaultId = pigeonVar_list[0] as! String
    let requestId = pigeonVar_list[1] as! String
    let reason = pigeonVar_list[2] as! WireMaterialReason
    let nonce = pigeonVar_list[3] as! FlutterStandardTypedData
    let deadlineMs = pigeonVar_list[4] as! Int64

    return WireMaterialContext(
      vaultId: vaultId,
      requestId: requestId,
      reason: reason,
      nonce: nonce,
      deadlineMs: deadlineMs
    )
  }
  func toList() -> [Any?] {
    return [
      vaultId,
      requestId,
      reason,
      nonce,
      deadlineMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WireKeyMaterial {
  /// At least 32 bytes, byte-identical on every call for a given [keyId].
  var material: FlutterStandardTypedData
  var keyId: String
  var cacheable: Bool
  var cacheTtlMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireKeyMaterial? {
    let material = pigeonVar_list[0] as! FlutterStandardTypedData
    let keyId = pigeonVar_list[1] as! String
    let cacheable = pigeonVar_list[2] as! Bool
    let cacheTtlMs = pigeonVar_list[3] as! Int64

    return WireKeyMaterial(
      material: material,
      keyId: keyId,
      cacheable: cacheable,
      cacheTtlMs: cacheTtlMs
    )
  }
  func toList() -> [Any?] {
    return [
      material,
      keyId,
      cacheable,
      cacheTtlMs,
    ]
  }
}

/// The recovery factor. Exactly one of [highEntropyBytes] or [passphrase] is set.
///
/// Pigeon has no sum type, so this is a tagged record; the Dart API in `envelock.dart` exposes
/// a proper sealed class over it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WireRecoveryFactor {
  /// 32 uniform bytes - a BIP-85 child key from the wallet seed, or equivalent.
  var highEntropyBytes: FlutterStandardTypedData? = nil
  /// A user-chosen passphrase. **Not** the host app's PIN (spec 0).
  var passphrase: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireRecoveryFactor? {
    let highEntropyBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])
    let passphrase: String? = nilOrValue(pigeonVar_list[1])

    return WireRecoveryFactor(
      highEntropyBytes: highEntropyBytes,
      passphrase: passphrase
    )
  }
  func toList() -> [Any?] {
    return [
      highEntropyBytes,
      passphrase,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WireSecurityInfo {
  /// Reported truthfully. `software` means the spec 2.3 security floor does not hold.
  var hardwareBacking: WireHardwareBacking
  var providerId: String
  var keyId: String
  var recoveryKind: WireRecoveryKind
  var enrolledAt: Int64
  var failedAttempts: Int64
  var lockedUntil: Int64
  var materialCachedUntil: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireSecurityInfo? {
    let hardwareBacking = pigeonVar_list[0] as! WireHardwareBacking
    let providerId = pigeonVar_list[1] as! String
    let keyId = pigeonVar_list[2] as! String
    let recoveryKind = pigeonVar_list[3] as! WireRecoveryKind
    let enrolledAt = pigeonVar_list[4] as! Int64
    let failedAttempts = pigeonVar_list[5] as! Int64
    let lockedUntil = pigeonVar_list[6] as! Int64
    let materialCachedUntil: Int64? = nilOrValue(pigeonVar_list[7])

    return WireSecurityInfo(
      hardwareBacking: hardwareBacking,
      providerId: providerId,
      keyId: keyId,
      recoveryKind: recoveryKind,
      enrolledAt: enrolledAt,
      failedAttempts: failedAttempts,
      lockedUntil: lockedUntil,
      materialCachedUntil: materialCachedUntil
    )
  }
  func toList() -> [Any?] {
    return [
      hardwareBacking,
      providerId,
      keyId,
      recoveryKind,
      enrolledAt,
      failedAttempts,
      lockedUntil,
      materialCachedUntil,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WireSecurityEvent {
  var type: String
  var hardware: WireHardwareBacking? = nil
  var usedCache: Bool? = nil
  var counted: Bool? = nil
  var from: String? = nil
  var to: String? = nil
  var reason: String? = nil
  var untilMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WireSecurityEvent? {
    let type = pigeonVar_list[0] as! String
    let hardware: WireHardwareBacking? = nilOrValue(pigeonVar_list[1])
    let usedCache: Bool? = nilOrValue(pigeonVar_list[2])
    let counted: Bool? = nilOrValue(pigeonVar_list[3])
    let from: String? = nilOrValue(pigeonVar_list[4])
    let to: String? = nilOrValue(pigeonVar_list[5])
    let reason: String? = nilOrValue(pigeonVar_list[6])
    let untilMs: Int64? = nilOrValue(pigeonVar_list[7])

    return WireSecurityEvent(
      type: type,
      hardware: hardware,
      usedCache: usedCache,
      counted: counted,
      from: from,
      to: to,
      reason: reason,
      untilMs: untilMs
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      hardware,
      usedCache,
      counted,
      from,
      to,
      reason,
      untilMs,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WireMaterialReason(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WireRecoveryReason(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WireHardwareBacking(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WireRecoveryKind(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WireVaultState(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WireErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return WireVaultConfig.fromList(self.readValue() as! [Any?])
    case 136:
      return WireVaultHandle.fromList(self.readValue() as! [Any?])
    case 137:
      return WireStateResult.fromList(self.readValue() as! [Any?])
    case 138:
      return WireMaterialContext.fromList(self.readValue() as! [Any?])
    case 139:
      return WireKeyMaterial.fromList(self.readValue() as! [Any?])
    case 140:
      return WireRecoveryFactor.fromList(self.readValue() as! [Any?])
    case 141:
      return WireSecurityInfo.fromList(self.readValue() as! [Any?])
    case 142:
      return WireSecurityEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WireMaterialReason {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WireRecoveryReason {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? WireHardwareBacking {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? WireRecoveryKind {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? WireVaultState {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? WireErrorCode {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? WireVaultConfig {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? WireVaultHandle {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? WireStateResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? WireMaterialContext {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? WireKeyMaterial {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? WireRecoveryFactor {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? WireSecurityInfo {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? WireSecurityEvent {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart calls native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EnvelockHostApi {
  /// Create a vault. Returns the id every later call uses to name it.
  func create(config: WireVaultConfig, completion: @escaping (Result<WireVaultHandle, Error>) -> Void)
  func dispose(vaultId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func state(vaultId: String, completion: @escaping (Result<WireStateResult, Error>) -> Void)
  func enroll(vaultId: String, factor: WireRecoveryFactor, completion: @escaping (Result<Void, Error>) -> Void)
  /// Primary path: one OS biometric prompt, cached material, works offline (spec 8.2).
  func unlock(vaultId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Recovery path. Provisions a fresh enclave key and rewraps the primary path in the same
  /// operation, so the next unlock is biometric-only (spec 8.4).
  func unlockWithRecovery(vaultId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func changeRecoveryFactor(vaultId: String, factor: WireRecoveryFactor, completion: @escaping (Result<Void, Error>) -> Void)
  func put(vaultId: String, recordId: String, value: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  func get(vaultId: String, recordId: String, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  func delete(vaultId: String, recordId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func list(vaultId: String, prefix: String, completion: @escaping (Result<[String], Error>) -> Void)
  /// Zeroize the in-memory DEK. Call from `AppLifecycleState.paused` (spec 11.3).
  func lock(vaultId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Irreversible: deletes the enclave key, envelope, cache and every record.
  func destroyVault(vaultId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func securityInfo(vaultId: String, completion: @escaping (Result<WireSecurityInfo, Error>) -> Void)
  /// Hand a provider callback's outcome back to native code.
  ///
  /// Native invokes the Dart provider through [EnvelockFlutterApi] and blocks a background
  /// thread waiting; this releases that wait. A null [errorCode] means success.
  func resolveCallback(requestId: String, payload: FlutterStandardTypedData?, payloadText: String?, errorCode: WireErrorCode?, errorMessage: String?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EnvelockHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `EnvelockHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EnvelockHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Create a vault. Returns the id every later call uses to name it.
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! WireVaultConfig
        api.create(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        api.dispose(vaultId: vaultIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let stateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.state\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        api.state(vaultId: vaultIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stateChannel.setMessageHandler(nil)
    }
    let enrollChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.enroll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enrollChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        let factorArg = args[1] as! WireRecoveryFactor
        api.enroll(vaultId: vaultIdArg, factor: factorArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enrollChannel.setMessageHandler(nil)
    }
    /// Primary path: one OS biometric prompt, cached material, works offline (spec 8.2).
    let unlockChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.unlock\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unlockChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        api.unlock(vaultId: vaultIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unlockChannel.setMessageHandler(nil)
    }
    /// Recovery path. Provisions a fresh enclave key and rewraps the primary path in the same
    /// operation, so the next unlock is biometric-only (spec 8.4).
    let unlockWithRecoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.unlockWithRecovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unlockWithRecoveryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        api.unlockWithRecovery(vaultId: vaultIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unlockWithRecoveryChannel.setMessageHandler(nil)
    }
    let changeRecoveryFactorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.changeRecoveryFactor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      changeRecoveryFactorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        let factorArg = args[1] as! WireRecoveryFactor
        api.changeRecoveryFactor(vaultId: vaultIdArg, factor: factorArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      changeRecoveryFactorChannel.setMessageHandler(nil)
    }
    let putChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.put\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      putChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        let recordIdArg = args[1] as! String
        let valueArg = args[2] as! FlutterStandardTypedData
        api.put(vaultId: vaultIdArg, recordId: recordIdArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      putChannel.setMessageHandler(nil)
    }
    let getChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.get\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        let recordIdArg = args[1] as! String
        api.get(vaultId: vaultIdArg, recordId: recordIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getChannel.setMessageHandler(nil)
    }
    let deleteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.delete\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        let recordIdArg = args[1] as! String
        api.delete(vaultId: vaultIdArg, recordId: recordIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteChannel.setMessageHandler(nil)
    }
    let listChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.list\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        let prefixArg = args[1] as! String
        api.list(vaultId: vaultIdArg, prefix: prefixArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listChannel.setMessageHandler(nil)
    }
    /// Zeroize the in-memory DEK. Call from `AppLifecycleState.paused` (spec 11.3).
    let lockChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.lock\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      lockChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        api.lock(vaultId: vaultIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      lockChannel.setMessageHandler(nil)
    }
    /// Irreversible: deletes the enclave key, envelope, cache and every record.
    let destroyVaultChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.destroyVault\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyVaultChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        api.destroyVault(vaultId: vaultIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      destroyVaultChannel.setMessageHandler(nil)
    }
    let securityInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.securityInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      securityInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vaultIdArg = args[0] as! String
        api.securityInfo(vaultId: vaultIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      securityInfoChannel.setMessageHandler(nil)
    }
    /// Hand a provider callback's outcome back to native code.
    ///
    /// Native invokes the Dart provider through [EnvelockFlutterApi] and blocks a background
    /// thread waiting; this releases that wait. A null [errorCode] means success.
    let resolveCallbackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.envelock.EnvelockHostApi.resolveCallback\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resolveCallbackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let payloadArg: FlutterStandardTypedData? = nilOrValue(args[1])
        let payloadTextArg: String? = nilOrValue(args[2])
        let errorCodeArg: WireErrorCode? = nilOrValue(args[3])
        let errorMessageArg: String? = nilOrValue(args[4])
        do {
          try api.resolveCallback(requestId: requestIdArg, payload: payloadArg, payloadText: payloadTextArg, errorCode: errorCodeArg, errorMessage: errorMessageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resolveCallbackChannel.setMessageHandler(nil)
    }
  }
}
/// Native calls Dart.
///
/// These are void and fire-and-forget on purpose: the native side is blocked on a semaphore,
/// and Dart answers by calling [EnvelockHostApi.resolveCallback] with the request id. Making
/// them return values instead would require the native side to await a Dart future from a
/// thread that is already blocked, which deadlocks.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol EnvelockFlutterApiProtocol {
  func onKeyMaterialRequested(ctx ctxArg: WireMaterialContext, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRecoveryFactorRequested(vaultId vaultIdArg: String, requestId requestIdArg: String, reason reasonArg: WireRecoveryReason, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSecurityEvent(vaultId vaultIdArg: String, event eventArg: WireSecurityEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class EnvelockFlutterApi: EnvelockFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onKeyMaterialRequested(ctx ctxArg: WireMaterialContext, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.envelock.EnvelockFlutterApi.onKeyMaterialRequested\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([ctxArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRecoveryFactorRequested(vaultId vaultIdArg: String, requestId requestIdArg: String, reason reasonArg: WireRecoveryReason, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.envelock.EnvelockFlutterApi.onRecoveryFactorRequested\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([vaultIdArg, requestIdArg, reasonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSecurityEvent(vaultId vaultIdArg: String, event eventArg: WireSecurityEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.envelock.EnvelockFlutterApi.onSecurityEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([vaultIdArg, eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
