// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum WireMaterialReason {
  enroll,
  unlock,
  rotate,
}

enum WireRecoveryReason {
  migrate,
  fallback,
  change,
}

enum WireHardwareBacking {
  secureEnclave,
  strongBox,
  tee,
  software,
}

enum WireRecoveryKind {
  highEntropy,
  passphrase,
}

enum WireVaultState {
  notEnrolled,
  locked,
  unlocked,
  lockedOut,
  needsRecovery,
}

/// How a provider rejected (spec §7.4).
///
/// Only [denied] counts toward lockout. Anything unrecognised is treated as [unavailable]:
/// retryable, because a flaky network must never march a legitimate user toward lockout.
enum WireErrorCode {
  cancelled,
  unavailable,
  denied,
  misconfigured,
  providerMaterialMismatch,
  providerKeyRotated,
  materialRejected,
  corruptData,
  unexpected,
}

class WireVaultConfig {
  WireVaultConfig({
    required this.providerId,
    this.directory,
    required this.autoLockMs,
    required this.callbackDeadlineMs,
    this.destroyAfterAttempts,
  });

  /// Namespaced into derivation. Changing it invalidates every existing vault.
  String providerId;

  /// App-private storage. Null lets the platform choose.
  String? directory;

  /// Inactivity timeout before the DEK is zeroized. `0` disables auto-lock.
  int autoLockMs;

  int callbackDeadlineMs;

  /// Failed recovery attempts before destruction. Null disables it. Passphrase vaults only.
  int? destroyAfterAttempts;

  Object encode() {
    return <Object?>[
      providerId,
      directory,
      autoLockMs,
      callbackDeadlineMs,
      destroyAfterAttempts,
    ];
  }

  static WireVaultConfig decode(Object result) {
    result as List<Object?>;
    return WireVaultConfig(
      providerId: result[0]! as String,
      directory: result[1] as String?,
      autoLockMs: result[2]! as int,
      callbackDeadlineMs: result[3]! as int,
      destroyAfterAttempts: result[4] as int?,
    );
  }
}

class WireStateResult {
  WireStateResult({
    required this.state,
    this.lockedUntilMs,
  });

  WireVaultState state;

  int? lockedUntilMs;

  Object encode() {
    return <Object?>[
      state,
      lockedUntilMs,
    ];
  }

  static WireStateResult decode(Object result) {
    result as List<Object?>;
    return WireStateResult(
      state: result[0]! as WireVaultState,
      lockedUntilMs: result[1] as int?,
    );
  }
}

class WireMaterialContext {
  WireMaterialContext({
    required this.requestId,
    required this.reason,
    required this.nonce,
    required this.deadlineMs,
  });

  String requestId;

  WireMaterialReason reason;

  /// 32 fresh bytes for challenge-response with your own backend. envelock never inspects any
  /// response; nothing in the key hierarchy depends on it.
  Uint8List nonce;

  int deadlineMs;

  Object encode() {
    return <Object?>[
      requestId,
      reason,
      nonce,
      deadlineMs,
    ];
  }

  static WireMaterialContext decode(Object result) {
    result as List<Object?>;
    return WireMaterialContext(
      requestId: result[0]! as String,
      reason: result[1]! as WireMaterialReason,
      nonce: result[2]! as Uint8List,
      deadlineMs: result[3]! as int,
    );
  }
}

class WireKeyMaterial {
  WireKeyMaterial({
    required this.material,
    required this.keyId,
    required this.cacheable,
    required this.cacheTtlMs,
  });

  /// At least 32 bytes, byte-identical on every call for a given [keyId].
  Uint8List material;

  String keyId;

  bool cacheable;

  int cacheTtlMs;

  Object encode() {
    return <Object?>[
      material,
      keyId,
      cacheable,
      cacheTtlMs,
    ];
  }

  static WireKeyMaterial decode(Object result) {
    result as List<Object?>;
    return WireKeyMaterial(
      material: result[0]! as Uint8List,
      keyId: result[1]! as String,
      cacheable: result[2]! as bool,
      cacheTtlMs: result[3]! as int,
    );
  }
}

/// The recovery factor. Exactly one of [highEntropyBytes] or [passphrase] is set.
///
/// Pigeon has no sum type, so this is a tagged record; the Dart API in `envelock.dart` exposes
/// a proper sealed class over it.
class WireRecoveryFactor {
  WireRecoveryFactor({
    this.highEntropyBytes,
    this.passphrase,
  });

  /// 32 uniform bytes — a BIP-85 child key from the wallet seed, or equivalent.
  Uint8List? highEntropyBytes;

  /// A user-chosen passphrase. **Not** the host app's PIN (spec §0).
  String? passphrase;

  Object encode() {
    return <Object?>[
      highEntropyBytes,
      passphrase,
    ];
  }

  static WireRecoveryFactor decode(Object result) {
    result as List<Object?>;
    return WireRecoveryFactor(
      highEntropyBytes: result[0] as Uint8List?,
      passphrase: result[1] as String?,
    );
  }
}

class WireSecurityInfo {
  WireSecurityInfo({
    required this.hardwareBacking,
    required this.providerId,
    required this.keyId,
    required this.recoveryKind,
    required this.enrolledAt,
    required this.failedAttempts,
    required this.lockedUntil,
    this.materialCachedUntil,
  });

  /// Reported truthfully. `software` means the spec §2.3 security floor does not hold.
  WireHardwareBacking hardwareBacking;

  String providerId;

  String keyId;

  WireRecoveryKind recoveryKind;

  int enrolledAt;

  int failedAttempts;

  int lockedUntil;

  int? materialCachedUntil;

  Object encode() {
    return <Object?>[
      hardwareBacking,
      providerId,
      keyId,
      recoveryKind,
      enrolledAt,
      failedAttempts,
      lockedUntil,
      materialCachedUntil,
    ];
  }

  static WireSecurityInfo decode(Object result) {
    result as List<Object?>;
    return WireSecurityInfo(
      hardwareBacking: result[0]! as WireHardwareBacking,
      providerId: result[1]! as String,
      keyId: result[2]! as String,
      recoveryKind: result[3]! as WireRecoveryKind,
      enrolledAt: result[4]! as int,
      failedAttempts: result[5]! as int,
      lockedUntil: result[6]! as int,
      materialCachedUntil: result[7] as int?,
    );
  }
}

class WireSecurityEvent {
  WireSecurityEvent({
    required this.type,
    this.hardware,
    this.usedCache,
    this.counted,
    this.from,
    this.to,
    this.reason,
    this.untilMs,
  });

  String type;

  WireHardwareBacking? hardware;

  bool? usedCache;

  bool? counted;

  String? from;

  String? to;

  String? reason;

  int? untilMs;

  Object encode() {
    return <Object?>[
      type,
      hardware,
      usedCache,
      counted,
      from,
      to,
      reason,
      untilMs,
    ];
  }

  static WireSecurityEvent decode(Object result) {
    result as List<Object?>;
    return WireSecurityEvent(
      type: result[0]! as String,
      hardware: result[1] as WireHardwareBacking?,
      usedCache: result[2] as bool?,
      counted: result[3] as bool?,
      from: result[4] as String?,
      to: result[5] as String?,
      reason: result[6] as String?,
      untilMs: result[7] as int?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is WireMaterialReason) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is WireRecoveryReason) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is WireHardwareBacking) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is WireRecoveryKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is WireVaultState) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is WireErrorCode) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is WireVaultConfig) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is WireStateResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is WireMaterialContext) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is WireKeyMaterial) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is WireRecoveryFactor) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is WireSecurityInfo) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is WireSecurityEvent) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : WireMaterialReason.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : WireRecoveryReason.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : WireHardwareBacking.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : WireRecoveryKind.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : WireVaultState.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : WireErrorCode.values[value];
      case 135: 
        return WireVaultConfig.decode(readValue(buffer)!);
      case 136: 
        return WireStateResult.decode(readValue(buffer)!);
      case 137: 
        return WireMaterialContext.decode(readValue(buffer)!);
      case 138: 
        return WireKeyMaterial.decode(readValue(buffer)!);
      case 139: 
        return WireRecoveryFactor.decode(readValue(buffer)!);
      case 140: 
        return WireSecurityInfo.decode(readValue(buffer)!);
      case 141: 
        return WireSecurityEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart calls native.
class EnvelockHostApi {
  /// Constructor for [EnvelockHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EnvelockHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Create the vault. Returns the resolved storage directory.
  Future<String> create(WireVaultConfig config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.create$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> dispose() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<WireStateResult> state() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.state$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as WireStateResult?)!;
    }
  }

  Future<void> enroll(WireRecoveryFactor factor) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.enroll$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[factor]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Primary path: one OS biometric prompt, cached material, works offline (spec §8.2).
  Future<void> unlock() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.unlock$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Recovery path. Provisions a fresh enclave key and rewraps the primary path in the same
  /// operation, so the next unlock is biometric-only (spec §8.4).
  Future<void> unlockWithRecovery() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.unlockWithRecovery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> changeRecoveryFactor(WireRecoveryFactor factor) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.changeRecoveryFactor$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[factor]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> put(String recordId, Uint8List value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.put$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[recordId, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Uint8List?> get(String recordId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.get$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[recordId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?);
    }
  }

  Future<void> delete(String recordId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.delete$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[recordId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<String>> list(String prefix) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.list$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[prefix]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<String>();
    }
  }

  /// Zeroize the in-memory DEK. Call from `AppLifecycleState.paused` (spec §11.3).
  Future<void> lock() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.lock$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Irreversible: deletes the enclave key, envelope, cache and every record.
  Future<void> destroyVault() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.destroyVault$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<WireSecurityInfo> securityInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.securityInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as WireSecurityInfo?)!;
    }
  }

  /// Hand a provider callback's outcome back to native code.
  ///
  /// Native invokes the Dart provider through [EnvelockFlutterApi] and blocks a background
  /// thread waiting; this releases that wait. A null [errorCode] means success.
  Future<void> resolveCallback(String requestId, Uint8List? payload, String? payloadText, WireErrorCode? errorCode, String? errorMessage) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.envelock.EnvelockHostApi.resolveCallback$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[requestId, payload, payloadText, errorCode, errorMessage]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Native calls Dart.
///
/// These are void and fire-and-forget on purpose: the native side is blocked on a semaphore,
/// and Dart answers by calling [EnvelockHostApi.resolveCallback] with the request id. Making
/// them return values instead would require the native side to await a Dart future from a
/// thread that is already blocked, which deadlocks.
abstract class EnvelockFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onKeyMaterialRequested(WireMaterialContext ctx);

  void onRecoveryFactorRequested(String requestId, WireRecoveryReason reason);

  void onSecurityEvent(WireSecurityEvent event);

  static void setUp(EnvelockFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.envelock.EnvelockFlutterApi.onKeyMaterialRequested$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.envelock.EnvelockFlutterApi.onKeyMaterialRequested was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final WireMaterialContext? arg_ctx = (args[0] as WireMaterialContext?);
          assert(arg_ctx != null,
              'Argument for dev.flutter.pigeon.envelock.EnvelockFlutterApi.onKeyMaterialRequested was null, expected non-null WireMaterialContext.');
          try {
            api.onKeyMaterialRequested(arg_ctx!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.envelock.EnvelockFlutterApi.onRecoveryFactorRequested$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.envelock.EnvelockFlutterApi.onRecoveryFactorRequested was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_requestId = (args[0] as String?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.envelock.EnvelockFlutterApi.onRecoveryFactorRequested was null, expected non-null String.');
          final WireRecoveryReason? arg_reason = (args[1] as WireRecoveryReason?);
          assert(arg_reason != null,
              'Argument for dev.flutter.pigeon.envelock.EnvelockFlutterApi.onRecoveryFactorRequested was null, expected non-null WireRecoveryReason.');
          try {
            api.onRecoveryFactorRequested(arg_requestId!, arg_reason!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.envelock.EnvelockFlutterApi.onSecurityEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.envelock.EnvelockFlutterApi.onSecurityEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final WireSecurityEvent? arg_event = (args[0] as WireSecurityEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.envelock.EnvelockFlutterApi.onSecurityEvent was null, expected non-null WireSecurityEvent.');
          try {
            api.onSecurityEvent(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
