// swift-tools-version: 5.9
import PackageDescription

// envelock for iOS - generated for github.com/ShareRing/envelock by the release workflow.
//
// Do not edit this file in the public repository: every release overwrites it. The template
// lives at public/Package.swift.tmpl in the private repository, and https://github.com/ShareRing/envelock/releases/download/v0.2.0/envelockFFI.zip / b6b7d61c4c4422e6d2d8021805c802a8d9e0ac3ae7c3c26a639a39d845bd5623 are
// filled in from the archive that was actually built for this tag.
//
// `envelockFFI` is the Rust core compiled for arm64 devices and for the simulator on both
// Apple silicon and Intel, downloaded from the GitHub Release rather than committed.
// `generated/envelock.swift` is the UniFFI binding, generated from that same compiled library
// and mirrored here so this package builds from a checkout alone.
let package = Package(
    name: "EnvelockCore",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "EnvelockCore", targets: ["EnvelockCore"])
    ],
    targets: [
        .binaryTarget(
            name: "envelockFFI",
            url: "https://github.com/ShareRing/envelock/releases/download/v0.2.0/envelockFFI.zip",
            checksum: "b6b7d61c4c4422e6d2d8021805c802a8d9e0ac3ae7c3c26a639a39d845bd5623"
        ),
        .target(
            name: "EnvelockCore",
            dependencies: ["envelockFFI"],
            path: "platform/ios",
            sources: ["Sources/Envelock", "generated/envelock.swift"]
        ),
        .testTarget(
            name: "EnvelockTests",
            dependencies: ["EnvelockCore"],
            path: "platform/ios/Tests/EnvelockTests"
        ),
    ]
)
