/**
 * The app's view of the vault: four SDK calls and no envelock import.
 *
 * `App.tsx` is the other half of the picture - the raw vault lifecycle, which is what `sdk.ts`
 * wraps. Switch between the two with the buttons at the top of the screen.
 *
 * ## What to watch for
 *
 * - **First launch enrolls silently.** The 12 words are generated by the SDK; the app only
 *   ever asks for them back with `getRecoveryFactor()`.
 * - **The first `getDocument` hits the fake backend, the rest do not.** After that the answer
 *   comes out of the vault, offline, behind one biometric prompt.
 * - **Backgrounding locks the vault**, so the next `getDocument` prompts again. Nothing in
 *   this file wires that up; the SDK does.
 */

import React, { useCallback, useEffect, useRef, useState } from 'react';
import {
  Modal,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  useColorScheme,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { VaultError } from '@sharering/react-native-envelock';

import { localDemoMaterialProvider, utf8Encode } from './providers';
import { ShareRingVaultSdk } from './sdk';

export default function SdkDemo(): React.JSX.Element {
  const dark = useColorScheme() === 'dark';
  const sdkRef = useRef<ShareRingVaultSdk | undefined>(undefined);

  const [log, setLog] = useState<string[]>([]);
  const [fatal, setFatal] = useState<string | undefined>();
  const [prompting, setPrompting] = useState(false);
  const [typed, setTyped] = useState('');
  const answer = useRef<((phrase: string) => void) | undefined>(undefined);
  const reject = useRef<(() => void) | undefined>(undefined);

  const append = useCallback((line: string) => {
    setLog((previous) => [line, ...previous].slice(0, 40));
  }, []);

  /** Only ever reached on a device that has never held the phrase - a restored backup. */
  const promptRecoveryPhrase = useCallback(async () => {
    setTyped('');
    setPrompting(true);
    return new Promise<string>((resolve, rejectPrompt) => {
      answer.current = (phrase) => {
        setPrompting(false);
        resolve(phrase);
      };
      reject.current = () => {
        setPrompting(false);
        // Dismissing is normal behaviour, not a failed attempt.
        rejectPrompt(VaultError.cancelled());
      };
    });
  }, []);

  useEffect(() => {
    let disposed = false;

    (async () => {
      try {
        const sdk = await ShareRingVaultSdk.initialize({
          appId: 'demo-miniapp',
          fetchDocument: fakeBackend,
          vaultOptions: {
            providerId: 'sharering-sdk-demo',
            // The one thing the app still owns. See providers.ts for why a locally stored
            // pepper is not a second factor.
            getKeyMaterial: localDemoMaterialProvider,
            promptRecoveryPhrase,
            onSecurityEvent: (event) => append(`- ${event.type}`),
          },
        });

        if (disposed) return;
        sdkRef.current = sdk;
        append('[ok] initialize - vault open and enrolled');
      } catch (e) {
        setFatal(String(e));
      }
    })();

    return () => {
      disposed = true;
      sdkRef.current = undefined;
    };
  }, [append, promptRecoveryPhrase]);

  const act = useCallback(
    async (label: string, body: (sdk: ShareRingVaultSdk) => Promise<string>) => {
      const sdk = sdkRef.current;
      if (!sdk) return;

      try {
        append(`[ok] ${label} - ${await body(sdk)}`);
      } catch (e) {
        const error = e as VaultError;
        append(
          error.code === 'cancelled'
            ? `- ${label} - cancelled by user (not counted)`
            : `[x] ${label} - ${error.code}: ${error.message}`,
        );
      }
    },
    [append],
  );

  if (fatal) {
    return (
      <SafeAreaView style={[styles.screen, dark && styles.screenDark]}>
        <ScrollView contentContainerStyle={styles.body}>
          <Text style={[styles.title, dark && styles.textDark]}>SDK failed to initialize</Text>
          <Text style={[styles.mono, dark && styles.textDark]}>{fatal}</Text>
        </ScrollView>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.screen, dark && styles.screenDark]}>
      <ScrollView contentContainerStyle={styles.body}>
        <Text style={[styles.title, dark && styles.textDark]}>ShareRing Vault SDK</Text>

        <View style={styles.row}>
          <Action
            label="Get document"
            onPress={() =>
              act('getDocument', async (sdk) => {
                const doc = await sdk.getDocument('passport');
                return `${doc.type} for ${doc.holder}`;
              })
            }
          />
          <Action
            label="Show recovery phrase"
            onPress={() => act('getRecoveryFactor', (sdk) => sdk.getRecoveryFactor())}
          />
          <Action
            label="Destroy"
            danger
            onPress={() =>
              act('destroy', async (sdk) => {
                await sdk.destroy();
                sdkRef.current = undefined;
                return 'everything deleted - irreversible';
              })
            }
          />
        </View>

        <View style={[styles.logBox, dark && styles.logBoxDark]}>
          {log.length === 0 ? (
            <Text style={[styles.mono, dark && styles.textDark]}>Waiting for initialize...</Text>
          ) : (
            log.map((line, i) => (
              <Text key={i} style={[styles.mono, dark && styles.textDark]}>
                {line}
              </Text>
            ))
          )}
        </View>
      </ScrollView>

      <Modal visible={prompting} transparent animationType="fade">
        <View style={styles.modalBackdrop}>
          <View style={[styles.modal, dark && styles.logBoxDark]}>
            <Text style={[styles.sectionTitle, dark && styles.textDark]}>
              Enter your 12 words
            </Text>
            <TextInput
              style={[styles.input, dark && styles.textDark]}
              multiline
              autoCapitalize="none"
              autoCorrect={false}
              placeholder="abandon ability able ..."
              value={typed}
              onChangeText={setTyped}
            />
            <View style={styles.row}>
              <Action label="Cancel" onPress={() => reject.current?.()} />
              <Action label="Recover" onPress={() => answer.current?.(typed)} />
            </View>
          </View>
        </View>
      </Modal>
    </SafeAreaView>
  );
}

/** Stands in for the ShareRing network. Called once per document, ever. */
async function fakeBackend(documentId: string): Promise<Uint8Array> {
  await new Promise<void>((resolve) => {
    setTimeout(() => resolve(), 300);
  });
  return utf8Encode(
    JSON.stringify({
      id: documentId,
      type: 'identity.passport',
      holder: 'Ada Lovelace',
      issuedAt: new Date().toISOString(),
    }),
  );
}

function Action({
  label,
  danger,
  onPress,
}: {
  label: string;
  danger?: boolean;
  onPress: () => void;
}) {
  return (
    <TouchableOpacity style={[styles.button, danger && styles.buttonDanger]} onPress={onPress}>
      <Text style={styles.buttonLabel}>{label}</Text>
    </TouchableOpacity>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f7f7f9' },
  screenDark: { backgroundColor: '#111114' },
  body: { padding: 16, gap: 4 },
  title: { fontSize: 28, fontWeight: '600', marginBottom: 8 },
  sectionTitle: { fontSize: 16, fontWeight: '600', marginBottom: 6 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  button: {
    backgroundColor: '#0f766e',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
  },
  buttonDanger: { backgroundColor: '#b91c1c' },
  buttonLabel: { color: 'white', fontWeight: '600' },
  logBox: { marginTop: 20, padding: 12, borderRadius: 8, backgroundColor: 'white', gap: 2 },
  logBoxDark: { backgroundColor: '#1c1c20' },
  mono: { fontFamily: 'Courier', fontSize: 11 },
  textDark: { color: '#e8e8ea' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: '#0008',
    justifyContent: 'center',
    padding: 24,
  },
  modal: { backgroundColor: 'white', borderRadius: 12, padding: 16, gap: 12 },
  input: {
    borderWidth: 1,
    borderColor: '#9993',
    borderRadius: 8,
    padding: 8,
    minHeight: 72,
  },
});
