/// The app's view of the vault: four SDK calls and no envelock import.
///
/// `lib/main.dart` is the other half of the picture - the raw vault lifecycle, which is what
/// `lib/sharering_vault_sdk.dart` wraps. The tabs at the bottom switch between them.
///
/// ## What to watch for
///
/// - **First launch enrolls silently.** The 12 words are generated by the SDK; the app only
///   ever asks for them back with `getRecoveryFactor()`.
/// - **The first `getDocument` hits the fake backend, the rest do not.** After that the answer
///   comes out of the vault, offline, behind one biometric prompt.
/// - **Backgrounding locks the vault**, so the next `getDocument` prompts again. Nothing in
///   this file wires that up; the SDK does.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/material.dart';

import 'providers.dart';
import 'sharering_vault_sdk.dart';

class SdkDemoScreen extends StatefulWidget {
  const SdkDemoScreen({super.key});

  @override
  State<SdkDemoScreen> createState() => _SdkDemoScreenState();
}

class _SdkDemoScreenState extends State<SdkDemoScreen> {
  final _log = <String>[];
  final _material = LocalDemoMaterialProvider();
  ShareRingVaultSdk? _sdk;
  String? _fatal;

  @override
  void initState() {
    super.initState();
    _initialize();
  }

  Future<void> _initialize() async {
    try {
      final sdk = await ShareRingVaultSdk.initialize(
        SdkOptions(
          appId: 'demo-miniapp',
          fetchDocument: _fakeBackend,
          vaultOptions: SdkVaultOptions(
            providerId: 'sharering-sdk-demo',
            // The one thing the app still owns. See providers.dart for why a locally stored
            // pepper is not a second factor.
            getKeyMaterial: _material.call,
            promptRecoveryPhrase: _askForPhrase,
            onSecurityEvent: (event) => _append('- $event'),
          ),
        ),
      );
      setState(() => _sdk = sdk);
      _append('[ok] initialize - vault open and enrolled');
    } catch (e) {
      setState(() => _fatal = '$e');
    }
  }

  /// Stands in for the ShareRing network. Called once per document, ever.
  Future<Uint8List> _fakeBackend(String documentId) async {
    await Future<void>.delayed(const Duration(milliseconds: 300));
    return Uint8List.fromList(utf8.encode(jsonEncode({
      'id': documentId,
      'type': 'identity.passport',
      'holder': 'Ada Lovelace',
      'issuedAt': DateTime.now().toIso8601String(),
    })));
  }

  /// Only ever reached on a device that has never held the phrase - a restored backup.
  Future<String> _askForPhrase(RecoveryReason reason) async {
    final controller = TextEditingController();
    final phrase = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Enter your 12 words (${reason.name})'),
        content: TextField(
          controller: controller,
          maxLines: 3,
          decoration: const InputDecoration(hintText: 'abandon ability able ...'),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.pop(context, controller.text),
            child: const Text('Recover'),
          ),
        ],
      ),
    );
    // Dismissing is normal behaviour, not a failed attempt.
    if (phrase == null) throw const VaultException.cancelled();
    return phrase;
  }

  void _append(String line) {
    if (!mounted) return;
    setState(() {
      _log.insert(0, line);
      if (_log.length > 40) _log.removeLast();
    });
  }

  Future<void> _act(String label, Future<String> Function(ShareRingVaultSdk) body) async {
    final sdk = _sdk;
    if (sdk == null) return;
    try {
      _append('[ok] $label - ${await body(sdk)}');
    } on VaultException catch (e) {
      _append(
        e.code == VaultErrorCode.cancelled
            ? '- $label - cancelled by user (not counted)'
            : '[x] $label - ${e.code.name}: ${e.message ?? ''}',
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final fatal = _fatal;
    if (fatal != null) {
      return Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Text('SDK failed to initialize:\n\n$fatal'),
          ),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(title: Text(_sdk == null ? 'initializing...' : 'ShareRing Vault SDK')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          Wrap(spacing: 8, runSpacing: 8, children: [
            FilledButton(
              onPressed: () => _act('getDocument', (sdk) async {
                final doc = await sdk.getDocument('passport');
                return '${doc['type']} for ${doc['holder']}';
              }),
              child: const Text('Get document'),
            ),
            FilledButton(
              onPressed: () => _act(
                'getRecoveryFactor',
                (sdk) async => await sdk.getRecoveryFactor(),
              ),
              child: const Text('Show recovery phrase'),
            ),
            FilledButton(
              style: FilledButton.styleFrom(
                backgroundColor: Theme.of(context).colorScheme.error,
              ),
              onPressed: () => _act('destroy', (sdk) async {
                await sdk.destroy();
                setState(() => _sdk = null);
                return 'everything deleted - irreversible';
              }),
              child: const Text('Destroy'),
            ),
          ]),
          const SizedBox(height: 16),
          Card(
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: _log.isEmpty
                    ? [const Text('Waiting for initialize...')]
                    : _log
                        .map((line) => Padding(
                              padding: const EdgeInsets.symmetric(vertical: 2),
                              child: Text(line, style: const TextStyle(fontSize: 12)),
                            ))
                        .toList(),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
