import EnvelockCore
import Foundation
import SwiftUI

/// The app's view of the vault: four SDK calls and no direct vault access.
///
/// `DemoApp.swift`'s own screen is the other half of the picture - the raw vault lifecycle,
/// which is what ``ShareRingVaultSdk`` wraps. The tab bar switches between them.
///
/// ## What to watch for
///
/// - **First launch enrolls silently.** The 12 words are generated by the SDK; the app only
///   ever asks for them back with `getRecoveryFactor()`.
/// - **The first "Get document" hits the fake backend, the rest do not.** After that the answer
///   comes out of the vault, offline, behind one Face ID prompt.
@MainActor
final class SdkDemoModel: ObservableObject {

    @Published var log: [String] = []
    @Published var fatal: String?
    @Published var prompting: FfiRecoveryReason?
    @Published var typed = ""

    private var sdk: ShareRingVaultSdk?

    /// The Rust core calls the recovery provider on a background thread and blocks it. The
    /// prompt answers through this semaphore; a blank answer means the user dismissed it.
    private let answered = DispatchSemaphore(value: 0)
    // Written on the main actor before `signal()`, read on the core's thread after `wait()`.
    // The semaphore is the ordering, which is why the unchecked annotation is honest here.
    nonisolated(unsafe) private var answer = ""

    func start() {
        guard sdk == nil, fatal == nil else { return }

        Task.detached { [weak self] in
            guard let self else { return }
            do {
                let sdk = try ShareRingVaultSdk.initialize(
                    SdkOptions(
                        appId: "demo-miniapp",
                        vaultOptions: SdkVaultOptions(
                            providerId: "sharering-sdk-demo",
                            // The one thing the app still owns. DemoProviders.swift explains why
                            // a locally-stored pepper is not a second factor.
                            material: LocalDemoMaterialProvider(),
                            promptRecoveryPhrase: { [weak self] reason in
                                self?.askForPhrase(reason) ?? ""
                            }
                        ),
                        fetchDocument: Self.fakeBackend
                    )
                )
                await MainActor.run {
                    self.sdk = sdk
                    self.append("[ok] initialize - vault open and enrolled")
                }
            } catch {
                await MainActor.run { self.fatal = "\(error)" }
            }
        }
    }

    func getDocument() {
        act("getDocument") { sdk in
            let doc = try sdk.getDocument("passport")
            return "\(doc["type"] ?? "?") for \(doc["holder"] ?? "?")"
        }
    }

    func showRecoveryPhrase() {
        act("getRecoveryFactor") { try $0.getRecoveryFactor() }
    }

    func destroy() {
        act("destroy") { sdk in
            try sdk.destroy()
            return "everything deleted - irreversible"
        }
    }

    /// Zeroize on background. The SDK owns the vault, so the app asks the SDK.
    func background() {
        sdk?.background()
    }

    func submitPhrase(_ phrase: String) {
        answer = phrase
        prompting = nil
        answered.signal()
    }

    // MARK: - Internals

    /// Called on the Rust core's thread. Blocks it until the prompt is answered, which is
    /// exactly the contract `promptRecoveryPhrase` documents.
    private nonisolated func askForPhrase(_ reason: FfiRecoveryReason) -> String {
        Task { @MainActor in
            self.typed = ""
            self.prompting = reason
        }
        answered.wait()
        return answer
    }

    private func act(_ label: String, _ body: @escaping (ShareRingVaultSdk) throws -> String) {
        guard let sdk else { return }

        Task.detached { [weak self] in
            let line: String
            do {
                line = "[ok] \(label) - \(try body(sdk))"
            } catch FfiVaultError.Cancelled {
                // Normal behaviour, and explicitly not a failed attempt (spec 7.4).
                line = "- \(label) - cancelled by user (not counted)"
            } catch {
                line = "[x] \(label) - \(error)"
            }
            await MainActor.run { self?.append(line) }
        }
    }

    private func append(_ line: String) {
        log.insert(line, at: 0)
        if log.count > 40 { log.removeLast() }
    }

    /// Stands in for the ShareRing network. Called once per document, ever.
    private static func fakeBackend(_ documentId: String) throws -> Data {
        try JSONSerialization.data(withJSONObject: [
            "id": documentId,
            "type": "identity.passport",
            "holder": "Ada Lovelace",
            "issuedAt": ISO8601DateFormatter().string(from: Date()),
        ])
    }
}

struct SdkDemoScreen: View {
    @StateObject private var model = SdkDemoModel()
    @Environment(\.scenePhase) private var scenePhase

    var body: some View {
        NavigationView {
            Group {
                if let fatal = model.fatal {
                    ScrollView { Text("SDK failed to initialize:\n\n\(fatal)").padding() }
                } else {
                    content
                }
            }
            .navigationTitle("ShareRing Vault SDK")
        }
        .onAppear { model.start() }
        .onChange(of: scenePhase) { phase in
            // `.background`, not `!= .active`: the Face ID sheet and the app switcher both make
            // the scene `.inactive` while the app is still in use, and the Face ID sheet is
            // raised by `unlock()` itself.
            if phase == .background { model.background() }
        }
        .alert("Enter your 12 words", isPresented: .constant(model.prompting != nil)) {
            TextField("abandon ability able ...", text: $model.typed)
            Button("Recover") { model.submitPhrase(model.typed) }
            // Dismissing is normal behaviour, not a failed attempt.
            Button("Cancel", role: .cancel) { model.submitPhrase("") }
        }
    }

    private var content: some View {
        List {
            Section("Documents") {
                Button("Get document") { model.getDocument() }
                Button("Show recovery phrase") { model.showRecoveryPhrase() }
            }

            Section("Danger") {
                Button("Destroy everything", role: .destructive) { model.destroy() }
            }

            Section("Log") {
                if model.log.isEmpty {
                    Text("Waiting for initialize...").foregroundStyle(.secondary)
                }
                ForEach(Array(model.log.enumerated()), id: \.offset) { _, line in
                    Text(line).font(.system(.caption, design: .monospaced))
                }
            }
        }
    }
}
