// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package network.sharering.envelock.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class WireMaterialReason(val raw: Int) {
  ENROLL(0),
  UNLOCK(1),
  ROTATE(2);

  companion object {
    fun ofRaw(raw: Int): WireMaterialReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WireRecoveryReason(val raw: Int) {
  MIGRATE(0),
  FALLBACK(1),
  CHANGE(2);

  companion object {
    fun ofRaw(raw: Int): WireRecoveryReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WireHardwareBacking(val raw: Int) {
  SECURE_ENCLAVE(0),
  STRONG_BOX(1),
  TEE(2),
  SOFTWARE(3);

  companion object {
    fun ofRaw(raw: Int): WireHardwareBacking? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WireRecoveryKind(val raw: Int) {
  HIGH_ENTROPY(0),
  PASSPHRASE(1);

  companion object {
    fun ofRaw(raw: Int): WireRecoveryKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WireVaultState(val raw: Int) {
  NOT_ENROLLED(0),
  LOCKED(1),
  UNLOCKED(2),
  LOCKED_OUT(3),
  NEEDS_RECOVERY(4);

  companion object {
    fun ofRaw(raw: Int): WireVaultState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * How a provider rejected (spec §7.4).
 *
 * Only [denied] counts toward lockout. Anything unrecognised is treated as [unavailable]:
 * retryable, because a flaky network must never march a legitimate user toward lockout.
 */
enum class WireErrorCode(val raw: Int) {
  CANCELLED(0),
  UNAVAILABLE(1),
  DENIED(2),
  MISCONFIGURED(3),
  PROVIDER_MATERIAL_MISMATCH(4),
  PROVIDER_KEY_ROTATED(5),
  MATERIAL_REJECTED(6),
  CORRUPT_DATA(7),
  UNEXPECTED(8);

  companion object {
    fun ofRaw(raw: Int): WireErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WireVaultConfig (
  /** Namespaced into derivation. Changing it invalidates every existing vault. */
  val providerId: String,
  /** App-private storage. Null lets the platform choose. */
  val directory: String? = null,
  /** Inactivity timeout before the DEK is zeroized. `0` disables auto-lock. */
  val autoLockMs: Long,
  val callbackDeadlineMs: Long,
  /** Failed recovery attempts before destruction. Null disables it. Passphrase vaults only. */
  val destroyAfterAttempts: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireVaultConfig {
      val providerId = pigeonVar_list[0] as String
      val directory = pigeonVar_list[1] as String?
      val autoLockMs = pigeonVar_list[2] as Long
      val callbackDeadlineMs = pigeonVar_list[3] as Long
      val destroyAfterAttempts = pigeonVar_list[4] as Long?
      return WireVaultConfig(providerId, directory, autoLockMs, callbackDeadlineMs, destroyAfterAttempts)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      providerId,
      directory,
      autoLockMs,
      callbackDeadlineMs,
      destroyAfterAttempts,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WireStateResult (
  val state: WireVaultState,
  val lockedUntilMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireStateResult {
      val state = pigeonVar_list[0] as WireVaultState
      val lockedUntilMs = pigeonVar_list[1] as Long?
      return WireStateResult(state, lockedUntilMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      lockedUntilMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WireMaterialContext (
  val requestId: String,
  val reason: WireMaterialReason,
  /**
   * 32 fresh bytes for challenge-response with your own backend. envelock never inspects any
   * response; nothing in the key hierarchy depends on it.
   */
  val nonce: ByteArray,
  val deadlineMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireMaterialContext {
      val requestId = pigeonVar_list[0] as String
      val reason = pigeonVar_list[1] as WireMaterialReason
      val nonce = pigeonVar_list[2] as ByteArray
      val deadlineMs = pigeonVar_list[3] as Long
      return WireMaterialContext(requestId, reason, nonce, deadlineMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      reason,
      nonce,
      deadlineMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WireKeyMaterial (
  /** At least 32 bytes, byte-identical on every call for a given [keyId]. */
  val material: ByteArray,
  val keyId: String,
  val cacheable: Boolean,
  val cacheTtlMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireKeyMaterial {
      val material = pigeonVar_list[0] as ByteArray
      val keyId = pigeonVar_list[1] as String
      val cacheable = pigeonVar_list[2] as Boolean
      val cacheTtlMs = pigeonVar_list[3] as Long
      return WireKeyMaterial(material, keyId, cacheable, cacheTtlMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      material,
      keyId,
      cacheable,
      cacheTtlMs,
    )
  }
}

/**
 * The recovery factor. Exactly one of [highEntropyBytes] or [passphrase] is set.
 *
 * Pigeon has no sum type, so this is a tagged record; the Dart API in `envelock.dart` exposes
 * a proper sealed class over it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WireRecoveryFactor (
  /** 32 uniform bytes — a BIP-85 child key from the wallet seed, or equivalent. */
  val highEntropyBytes: ByteArray? = null,
  /** A user-chosen passphrase. **Not** the host app's PIN (spec §0). */
  val passphrase: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireRecoveryFactor {
      val highEntropyBytes = pigeonVar_list[0] as ByteArray?
      val passphrase = pigeonVar_list[1] as String?
      return WireRecoveryFactor(highEntropyBytes, passphrase)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      highEntropyBytes,
      passphrase,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WireSecurityInfo (
  /** Reported truthfully. `software` means the spec §2.3 security floor does not hold. */
  val hardwareBacking: WireHardwareBacking,
  val providerId: String,
  val keyId: String,
  val recoveryKind: WireRecoveryKind,
  val enrolledAt: Long,
  val failedAttempts: Long,
  val lockedUntil: Long,
  val materialCachedUntil: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireSecurityInfo {
      val hardwareBacking = pigeonVar_list[0] as WireHardwareBacking
      val providerId = pigeonVar_list[1] as String
      val keyId = pigeonVar_list[2] as String
      val recoveryKind = pigeonVar_list[3] as WireRecoveryKind
      val enrolledAt = pigeonVar_list[4] as Long
      val failedAttempts = pigeonVar_list[5] as Long
      val lockedUntil = pigeonVar_list[6] as Long
      val materialCachedUntil = pigeonVar_list[7] as Long?
      return WireSecurityInfo(hardwareBacking, providerId, keyId, recoveryKind, enrolledAt, failedAttempts, lockedUntil, materialCachedUntil)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hardwareBacking,
      providerId,
      keyId,
      recoveryKind,
      enrolledAt,
      failedAttempts,
      lockedUntil,
      materialCachedUntil,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WireSecurityEvent (
  val type: String,
  val hardware: WireHardwareBacking? = null,
  val usedCache: Boolean? = null,
  val counted: Boolean? = null,
  val from: String? = null,
  val to: String? = null,
  val reason: String? = null,
  val untilMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WireSecurityEvent {
      val type = pigeonVar_list[0] as String
      val hardware = pigeonVar_list[1] as WireHardwareBacking?
      val usedCache = pigeonVar_list[2] as Boolean?
      val counted = pigeonVar_list[3] as Boolean?
      val from = pigeonVar_list[4] as String?
      val to = pigeonVar_list[5] as String?
      val reason = pigeonVar_list[6] as String?
      val untilMs = pigeonVar_list[7] as Long?
      return WireSecurityEvent(type, hardware, usedCache, counted, from, to, reason, untilMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      hardware,
      usedCache,
      counted,
      from,
      to,
      reason,
      untilMs,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WireMaterialReason.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WireRecoveryReason.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WireHardwareBacking.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WireRecoveryKind.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WireVaultState.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WireErrorCode.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireVaultConfig.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireStateResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireMaterialContext.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireKeyMaterial.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireRecoveryFactor.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireSecurityInfo.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WireSecurityEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WireMaterialReason -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is WireRecoveryReason -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is WireHardwareBacking -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is WireRecoveryKind -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is WireVaultState -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is WireErrorCode -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is WireVaultConfig -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is WireStateResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is WireMaterialContext -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is WireKeyMaterial -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is WireRecoveryFactor -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is WireSecurityInfo -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is WireSecurityEvent -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart calls native.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface EnvelockHostApi {
  /** Create the vault. Returns the resolved storage directory. */
  fun create(config: WireVaultConfig, callback: (Result<String>) -> Unit)
  fun dispose(callback: (Result<Unit>) -> Unit)
  fun state(callback: (Result<WireStateResult>) -> Unit)
  fun enroll(factor: WireRecoveryFactor, callback: (Result<Unit>) -> Unit)
  /** Primary path: one OS biometric prompt, cached material, works offline (spec §8.2). */
  fun unlock(callback: (Result<Unit>) -> Unit)
  /**
   * Recovery path. Provisions a fresh enclave key and rewraps the primary path in the same
   * operation, so the next unlock is biometric-only (spec §8.4).
   */
  fun unlockWithRecovery(callback: (Result<Unit>) -> Unit)
  fun changeRecoveryFactor(factor: WireRecoveryFactor, callback: (Result<Unit>) -> Unit)
  fun put(recordId: String, value: ByteArray, callback: (Result<Unit>) -> Unit)
  fun get(recordId: String, callback: (Result<ByteArray?>) -> Unit)
  fun delete(recordId: String, callback: (Result<Unit>) -> Unit)
  fun list(prefix: String, callback: (Result<List<String>>) -> Unit)
  /** Zeroize the in-memory DEK. Call from `AppLifecycleState.paused` (spec §11.3). */
  fun lock(callback: (Result<Unit>) -> Unit)
  /** Irreversible: deletes the enclave key, envelope, cache and every record. */
  fun destroyVault(callback: (Result<Unit>) -> Unit)
  fun securityInfo(callback: (Result<WireSecurityInfo>) -> Unit)
  /**
   * Hand a provider callback's outcome back to native code.
   *
   * Native invokes the Dart provider through [EnvelockFlutterApi] and blocks a background
   * thread waiting; this releases that wait. A null [errorCode] means success.
   */
  fun resolveCallback(requestId: String, payload: ByteArray?, payloadText: String?, errorCode: WireErrorCode?, errorMessage: String?)

  companion object {
    /** The codec used by EnvelockHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `EnvelockHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EnvelockHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.create$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as WireVaultConfig
            api.create(configArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dispose{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.state$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.state{ result: Result<WireStateResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.enroll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val factorArg = args[0] as WireRecoveryFactor
            api.enroll(factorArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.unlock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unlock{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.unlockWithRecovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unlockWithRecovery{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.changeRecoveryFactor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val factorArg = args[0] as WireRecoveryFactor
            api.changeRecoveryFactor(factorArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.put$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordIdArg = args[0] as String
            val valueArg = args[1] as ByteArray
            api.put(recordIdArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.get$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordIdArg = args[0] as String
            api.get(recordIdArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.delete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordIdArg = args[0] as String
            api.delete(recordIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.list$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            api.list(prefixArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.lock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.lock{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.destroyVault$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.destroyVault{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.securityInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.securityInfo{ result: Result<WireSecurityInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.envelock.EnvelockHostApi.resolveCallback$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val payloadArg = args[1] as ByteArray?
            val payloadTextArg = args[2] as String?
            val errorCodeArg = args[3] as WireErrorCode?
            val errorMessageArg = args[4] as String?
            val wrapped: List<Any?> = try {
              api.resolveCallback(requestIdArg, payloadArg, payloadTextArg, errorCodeArg, errorMessageArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native calls Dart.
 *
 * These are void and fire-and-forget on purpose: the native side is blocked on a semaphore,
 * and Dart answers by calling [EnvelockHostApi.resolveCallback] with the request id. Making
 * them return values instead would require the native side to await a Dart future from a
 * thread that is already blocked, which deadlocks.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class EnvelockFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EnvelockFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onKeyMaterialRequested(ctxArg: WireMaterialContext, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.envelock.EnvelockFlutterApi.onKeyMaterialRequested$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(ctxArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRecoveryFactorRequested(requestIdArg: String, reasonArg: WireRecoveryReason, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.envelock.EnvelockFlutterApi.onRecoveryFactorRequested$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestIdArg, reasonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSecurityEvent(eventArg: WireSecurityEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.envelock.EnvelockFlutterApi.onSecurityEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
